// Generated by Nuxt Auto Form

import type { Component } from '@vue/runtime-core'

declare module 'zod' {
  /** Global configuration added by `nuxt-auto-form` Nuxt module */
  interface GlobalMeta {
    /** Auto-form specific configuration */
    theme?: {
      /** Float the input box to the right of the label */
      floatRight?: boolean
      /**
       * Apply `w-full` class to all input components by default.
       * @default true
       */
      wFull?: boolean
    }

    /**
     * Configuration for the inner Input component.
     *
     * @remarks Added by `nuxt-auto-form`
     */
    input?: {
      /**
       * Vue component or component name used to render the input.
       */
      component?: string | Component
      /**
       * Props forwarded to the input component at render time.
       * These are merged with the module's default props - user props take precedence.
       */
      props?: Record<string, any>
    }

    /**
     * Field label displayed in the form's label row.
     * Maps directly to `UFormField.label`.
     *
     * @remarks Added by `nuxt-auto-form`
     * @default Field name in PascalCase with spaces
     * @see https://ui.nuxt.com/components/form-field#description
     */
    title?: string

    /**
     * Marks the field as required in the UI (asterisk, aria-required).
     * Validation is not enforced here; use `zod` refinements for that.
     *
     * @remarks Added by `nuxt-auto-form`
     * @see https://ui.nuxt.com/components/form-field#required
     */
    required?: boolean

    /**
     * Supporting text displayed between the label and the input control.
     *
     * @remarks Added by `nuxt-auto-form`
     * @see https://ui.nuxt.com/components/form-field#description
     */
    description?: string

    /**
     * Short inline hint shown next to the label.
     *
     * @remarks Added by `nuxt-auto-form`
     * @see https://ui.nuxt.com/components/form-field#hint
     */
    hint?: string

    /**
     * Help text displayed below the input field.
     *
     * @remarks Added by `nuxt-auto-form`
     * @see https://ui.nuxt.com/components/form-field#help
     */
    help?: string

    /**
     * Intend to use `$t` function of `vue-i18n` to translate `title`, `description`, `hint`, and `help` texts.
     *
     * @remarks Added by `nuxt-auto-form`
     */
    i18n?: boolean
  }
}

export {}
